backend:
  name: git-gateway
  branch: main
media_folder: "media"
public_folder: "media"
publish_mode: editorial_workflow
collections:
  - label: "About"
    name: "about"
    files:
    - label: "About"
      name: "info"
      format: 'json'
      file: "content/about.json"
      fields:
        - {label: "Message", name: message, widget: string}
- label: "Profile"
  name: "profile"
  widget: "object"
  summary: '{{fields.name}}: {{fields.birthdate}}'
  fields:
    - {label: "Public", name: "public", widget: "boolean", default: true}
    - {label: "Name", name: "name", widget: "string"}
    - label: "Birthdate"
      name: "birthdate"
      widget: "date"
      default: ""
      format: "MM/DD/YYYY"
    - label: "Address"
      name: "address"
      widget: "object"
      collapsed: true
      fields: 
        - {label: "Street Address", name: "street", widget: "string"}
        - {label: "City", name: "city", widget: "string"}
        - {label: "Postal Code", name: "post-code", widget: "string"}