backend:
  name: git-gateway
  branch: main
media_folder: src/static/img
public_folder: /static/img
local_backend: true
collections:
  - label: Blog
    name: blog
    folder: src/posts
    create: true
    identifier_field: name
    fields:
      - label: Name
        name: name
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Featured Image
        name: thumbnail
        widget: image
      - label: Body
        name: body
        widget: markdown
  - label: Profile
    name: profile
    folder: src/profile
    create: true
    widget: object
    summary: '{{fields.name}}: {{fields.birthdate}}'
    fields:
      - label: Public
        name: public
        widget: boolean
        default: true
      - label: Name
        name: name
        widget: string
      - label: Birthdate
        name: birthdate
        widget: date
        default: ''
        format: MM/DD/YYYY
      - label: Address
        name: address
        widget: object
        collapsed: true
        fields:
          - label: Street Address
            name: street
            widget: string
          - label: City
            name: city
            widget: string
          - label: Postal Code
            name: post-code
            widget: string
